# Configuration for SIC Evaluation 

[paths]
batch_filepath = "gs://<insert-location>/evaluation_data/TLFS_evaluation_data_IT2.csv"
output_filepath = "gs://<insert-location>/"

[parameters]
test_mode = true
test_num = 175
rows_to_skip = 13099

[column_names]
payload_unique_id = "unique_id"
payload_job_title = "soc2020_job_title"
payload_job_description = "soc2020_job_description"
payload_industry_description = "sic2007_employee"


unique_id = "unique_id"
sic_ind_occ1 = "sic_ind_occ1"         # Analysis SIC code column
sic_ind_occ2 = "sic_ind_occ2"         # Analysis SIC code column
sic_ind_occ3 = "sic_ind_occ3"         # Analysis SIC code column
coding_flag = "sic_ind_code_flag"   # Analysis column for KB/CC/MC flag

