# Configuration for the SIC Evaluation Script

[paths]
# Input path for the expert-coded gold standard data (relative to project root)
batch_filepath = "data/evaluation_data/coding_df_with_validated.csv"
# batch_filepath = "gs://survey_assist_sandbox_data/evaluation_data/coding_df_with_validated.csv"

# Output file for batch processing results
output_filepath = "data/analysis_outputs/output.jsonl" # Changed from .csv to .jsonl
# output_filepath = "gs://survey_assist_sandbox_data/"

[parameters]
test_mode = true
test_num = 2
rows_to_skip = 0

[column_names]
# --- Column names from the input CSV to be used for API payload ---
payload_unique_id = "unique_id"
payload_job_title = "soc2020_job_title"
payload_job_description = "soc2020_job_description"
payload_industry_description = "sic2007_employee"

[api_settings]
base_url = "https://<API Domain>/survey-assist/classify"
# llm_model = "gemini" # Example if you want to configure this too
# request_type = "sic" # Example

[logging]
# Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
level = "INFO"
# Optional: Log file path (relative to project root). If commented out, logs to console.
# file = "logs/evaluation.log" # Corrected path example
format = "%(asctime)s - %(levelname)s - %(name)s - %(message)s"